### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by johntom** [cianclarke/node-gallery#13]
Hi,
Just installed repo and Albums directory dispays each with a photo along with Photos.
Clicking on Doo%20Loug brings up http://localhost:3000/gallery/Doo%20Lough.jpg
Clicking on Ireland/West http://localhost:3000/gallery//Ireland/West%20Coast
brings up Failed to load album /Ireland/West Coast
same for all other albums.
Thanks,
John

**Comment by cianclarke** [comment]
Thanks John - as you've probably gathered, I've only just ported this to Express 4 & haven't tried much on Windows yet. 
Can you paste any console log from the error? 
There should be an error message and an error object with the path that it tried loading the image from in the response - any other info would help. 
If you need to obscure your directory structure, please by all means do - but need to see the paths!
Thanks

**Comment by cianclarke** [comment]
John - just tried this on a windows laptop. The only problem I ran into was the thumbnails didn't display, as image magick wasn't installed on the laptop. See https://github.com/cianclarke/node-gallery#imagemagick

Everything else seemed to work OK. If you're still having issues, let me know

**Comment by johntom** [comment]
Hi,

Just installed on my Home windows 8.1 computer and have the same issues.  Imagemagic installs fine and covert.exe at cmd displays help file.

default view is attached.

When I click on any of the galleries I get the following see below.

Great work. I have a co-authored repo at https://github.com/SharePointOscar/MEANS

I'll help in any way possible.

John

**Comment by johntom** [comment]
I'm debugging now with webstorm and it looks like a path issue

"C:\Program Files (x86)\JetBrains\WebStorm 9.0.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" --debug-brk=53482 --nolazy app.js

debugger listening on port 53482

node-gallery listening on localhost:3000

{ name: 'Photo Gallery',

  prettyName: 'Photo Gallery',

  isRoot: true,

  path: 'photos',

  photos: [ { name: 'Doo Lough', path: '/Doo Lough.jpg', exif: undefined } ],

  albums: 

   [ { name: '\\Ireland',

       prettyName: 'Ireland',

       description: 'Photos of Ireland.',

       hash: '\\Ireland',

       path: '\\Ireland',

       photos: [Object],

       albums: [],

       thumb: '\\Ireland/East%20Coast/_MG_9909.JPG' },

     { name: '\\Ireland\\West Coast',

       prettyName: '\\Ireland\\West Coast',

       description: '',

       hash: '\\Ireland\\West Coast',

       path: '\\Ireland\\West Coast',

       photos: [Object],

       albums: [] },

     { name: '\\Ireland\\East Coast',

       prettyName: '\\Ireland\\East Coast',

       description: '',

       hash: '\\Ireland\\East Coast',

       path: '\\Ireland\\East Coast',

       photos: [Object],

       albums: [] },

     { name: '\\Ireland\\Co. Dublin',

       prettyName: '\\Ireland\\Co. Dublin',

       description: '',

       hash: '\\Ireland\\Co. Dublin',

       path: '\\Ireland\\Co. Dublin',

       photos: [Object],

       albums: [] } ] }

{ name: '\\Ireland\\West Coast',

  prettyName: '\\Ireland\\West Coast',

  description: '',

  hash: '\\Ireland\\West Coast',

  path: '\\Ireland\\West Coast',

  photos: 

   [ { name: '357_G',

       path: '\\Ireland\\West Coast/357_G.jpg',

       exif: undefined },

     { name: '358_G',

       path: '\\Ireland\\West Coast/358_G.jpg',

       exif: undefined },

     { name: '386_G',

       path: '\\Ireland\\West Coast/386_G.jpg',

       exif: undefined },

     { name: 'MG_4100',

       path: '\\Ireland\\West Coast/MG_4100.jpg',

       exif: undefined },

     { name: 'MG_4174',

       path: '\\Ireland\\West Coast/MG_4174.jpg',

       exif: undefined },

     { name: '_MG_84201',

       path: '\\Ireland\\West Coast/_MG_84201.jpg',

       exif: undefined },

     { name: '_MG_86161',

       path: '\\Ireland\\West Coast/_MG_86161.jpg',

       exif: undefined },

     { name: '_MG_86321',

       path: '\\Ireland\\West Coast/_MG_86321.jpg',

       exif: undefined } ],

  albums: [] }

{ name: '\\Ireland\\East Coast',

  prettyName: '\\Ireland\\East Coast',

  description: '',

  hash: '\\Ireland\\East Coast',

  path: '\\Ireland\\East Coast',

  photos: 

   [ { name: 'MG_0367',

       path: '\\Ireland\\East Coast/MG_0367.jpg',

       exif: undefined },

     { name: 'MG_9910',

       path: '\\Ireland\\East Coast/MG_9910.jpg',

       exif: undefined },

     { name: '_MG_9909',

       path: '\\Ireland\\East Coast/_MG_9909.JPG',

       exif: undefined },

     { name: '_MG_9916',

       path: '\\Ireland\\East Coast/_MG_9916.JPG',

       exif: undefined } ],

  albums: [] }

{ name: '\\Ireland\\Co. Dublin',

  prettyName: '\\Ireland\\Co. Dublin',

  description: '',

  hash: '\\Ireland\\Co. Dublin',

  path: '\\Ireland\\Co. Dublin',

  photos: 

   [ { name: 'IMG_0179 _Small_',

       path: '\\Ireland\\Co. Dublin/IMG_0179 _Small_.JPG',

       exif: undefined },

     { name: 'IMG_0223 _Medium_',

       path: '\\Ireland\\Co. Dublin/IMG_0223 _Medium_.JPG',

       exif: undefined },

     { name: 'IMG_0226 _Medium_',

       path: '\\Ireland\\Co. Dublin/IMG_0226 _Medium_.JPG',

       exif: undefined },

     { name: '_MG_3169',

       path: '\\Ireland\\Co. Dublin/_MG_3169.jpg',

       exif: undefined },

     { name: '_MG_3172',

       path: '\\Ireland\\Co. Dublin/_MG_3172.jpg',

       exif: undefined },

     { name: '_MG_3177',

       path: '\\Ireland\\Co. Dublin/_MG_3177.jpg',

       exif: undefined },

     { name: '_MG_9828 _Small_',

       path: '\\Ireland\\Co. Dublin/_MG_9828 _Small_.jpg',

       exif: undefined } ],

  albums: [] }

**Comment by cianclarke** [comment]
Thanks for the help in debugging! Do you think it's the path separator issue on unix v.s. windows? I may have hardcoded a / v.s. a \ in places, e.g. https://github.com/cianclarke/node-gallery/blame/master/lib/photo.js#L13

Also, are you sure you're using the latest version? I note in your email mention of `prettyName` in the output, an attribute that only existed in the old 0.3.* version IIRC

Cheers
Cian

**Comment by johntom** [comment]
Really odd, I downed twice before with a git clone  and it was using express 3.  Just did it again and now it has express 4 with slightly modified directory layout. Will get back...

**Comment by cianclarke** [comment]
..that sounds more like it :) Great! let me know

On 29 January 2015 at 17:40, John Tomaselli <notifications@github.com>
wrote:

> Really odd, I downed twice before with a git clone and it was using
> express 3. Just did it again and now it has express 4 with slightly
> modified directory layout. Will get back...
>
>
>
> From: Cian Clarke [mailto:notifications@github.com]
> Sent: Thursday, January 29, 2015 4:55 PM
> To: cianclarke/node-gallery
> Cc: John R. Tomaselli
> Subject: Re: [node-gallery] windows 7 (#13)
>
>
>
> Thanks for the help in debugging! Do you think it's the path separator
> issue on unix v.s. windows? I may have hardcoded a / v.s. a \ in places,
> e.g.
> https://github.com/cianclarke/node-gallery/blame/master/lib/photo.js#L13
>
> Also, are you sure you're using the latest version? I note in your email
> mention of prettyName in the output, an attribute that only existed in the
> old 0.3.* version IIRC
>
> Cheers
> Cian
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/cianclarke/node-gallery/issues/13#issuecomment-72112217>
> . <
> https://github.com/notifications/beacon/ABylgF0MExlguaFS0_BivVHXJsofRWRnks5nmqPMgaJpZM4DYqr6.gif>
>
>
> ________________________________
>
> No virus found in this message.
> Checked by AVG - www.avg.com
> Version: 2015.0.5645 / Virus Database: 4273/9007 - Release Date: 01/27/15
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cianclarke/node-gallery/issues/13#issuecomment-72119216>
> .
>



-- 
--------------------------------------
http://www.cianclarke.com
@cianclarke <http://www.twitter.com/cianclarke> | *On Github
<http://www.github.com/cianclarke>*

**Comment by johntom** [comment]
Closer. First view

 

 

 

When I click on albums

 

 

 

Then When I click on an album

**Comment by johntom** [comment]
I restarted webstorm and made sure convert worked from terminal. It's all working now! Looks great.

Thanks,

John

**Comment by cianclarke** [comment]
That's great, John - glad to hear it!

**Comment by johntom** [comment]
Fantastic photos.

**Comment by cianclarke** [comment]
Glad you like :) I'm in the process of converting my personal site at cianclarke.com to use node gallery & express

**Comment by johntom** [comment]
I wrote a  cms with the MEANS stack mentioned before and used the angular directive for http://wallopslider.github.io/.
