### ISSUE TITLE
Getting "Unhandled error event"

### ISSUE THREAD

**Issue by anselanza** [cianclarke/node-gallery#14]
I have installed your module into a new project, and installed the required dependencies. Then I've implemented an index.js file which is exactly like your app.js file, except with the require('node-gallery') changed as indicated.

It seems to run fine, but when I hit the gallery at localhost:3000/gallery, node crashes with:

node-gallery listening on localhost:3000

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by anselanza** [comment]
Oops, figured it out. It was actually because Imagemagick wasn't installed on my machine.

**Comment by cianclarke** [comment]
Great! Let me know if you experience any other issues
